Q1: WHO IS THE SENIOR MOST EMPLOYEE BASED ON THE JOB TITTLE ?

 SELECT * FROM EMPLOYEE
 ORDER BY LEVELS DESC
 LIMIT 1
 
 Q 2: WHICH COUNTRIES HAVE MOST MOST INVOICES?
 
SELECT COUNT(*) AS C, BILLING_COUNTRY
FROM INVOICE GROUP BY BILLING_COUNTRY
ORDER BY C DESC

 Q 3: WHAT ARE THE TOP 3 VALUES OF TOTAL INVOICE?
 
 SELECT * FROM INVOICE 
 ORDER BY TOTAL DESC
 LIMIT 3
 
 Q 4: WHICH CITY HAS THE BEST CUSTOMERS? WE WOULD LIKE TO THROW A PROMOTIONAL MUSIC FESTIVAL IN THE CITY 
 WE MADE THE MOST MONEY . WRITE A QUERY THAT RETURNS ONE CITY THAT HAS THE HIGHEST SUM OF INVOICE TOTALS.
 RETURN BOTH THE CITY NAME & SUM OF ALL INVOICE TOTALS.
 
 SELECT COUNT(TOTAL) AS INVOICE_TOTAL,
 BILLING_CITY FROM INVOICE 
 GROUP BY BILLING_CITY 
 ORDER BY INVOICE_TOTAL DESC
 
 Q 5: WHO IS THE BEST CUSTOMER ? THE CUSTOMER WHO HAS SPENT THE MOST MONEY WILL BE DECLARED AS THE BEST
 CUSTOMER. WRITE A QUERY THAT RETURNS THE PERSON WHO HAS SPENT THE MOST MEONEY .
 
 SELECT 
    CUSTOMER.CUSTOMER_ID, 
    CUSTOMER.FIRST_NAME, 
    CUSTOMER.LAST_NAME, 
    SUM(INVOICE.TOTAL) AS TOTAL
FROM CUSTOMER
JOIN INVOICE 
    ON CUSTOMER.CUSTOMER_ID = INVOICE.CUSTOMER_ID
GROUP BY CUSTOMER.CUSTOMER_ID, CUSTOMER.FIRST_NAME, CUSTOMER.LAST_NAME
ORDER BY TOTAL DESC
LIMIT 1
 
 